#!/usr/bin/env bash

rm -rf dist/*
esbuild src/index.ts --bundle --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/mono-context.js --sourcemap --format=iife --global-name=MonoContext \
  && esbuild src/index.ts --bundle --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/mono-context.min.js --minify --format=iife --global-name=MonoContext \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/mono-context.d.ts \
  && refup dist/mono-context.js MonoContext \
  && refup dist/mono-context.min.js MonoContext \
  || exit 1
